FROM python:3.8

ARG TAG=local

WORKDIR /usr/src/


# VARIABLES PREDEFINIDAS
ENV SENSORIAL_RESTAPI_VERSION=${TAG}

ENV SENSORIAL_RESTAPI_PYTHON_HOST=0.0.0.0
ENV SENSORIAL_RESTAPI_PYTHON_PORT=${PORT:-5000}
ENV SENSORIAL_RESTAPI_PYTHON_GUNICORN_WORKERS=1
ENV SENSORIAL_RESTAPI_PYTHON_GUNICORN_CONNECTIONS=1000
ENV SENSORIAL_RESTAPI_PYTHON_NOMBRE_APP=app
ENV SENSORIAL_RESTAPI_PYTHON_NOMBRE_FUNCION_APP=app


# EJECUCION
CMD gunicorn \
    -b ${SENSORIAL_RESTAPI_PYTHON_HOST}:${SENSORIAL_RESTAPI_PYTHON_PORT} \
    --reload \
    --workers=${SENSORIAL_RESTAPI_PYTHON_GUNICORN_WORKERS} \
    --worker-connections=${SENSORIAL_RESTAPI_PYTHON_GUNICORN_CONNECTIONS} \
    ${SENSORIAL_RESTAPI_PYTHON_NOMBRE_APP}:${SENSORIAL_RESTAPI_PYTHON_NOMBRE_FUNCION_APP}

EXPOSE ${SENSORIAL_RESTAPI_PYTHON_PORT}


# DEPENDENCIAS
RUN pip install compile --upgrade pip

COPY ./requirements.txt .
COPY ./files ./files

RUN pip install -r requirements.txt
RUN rm requirements.txt


# COMPILACION
COPY ./apps ./src/apps
COPY ./app.py ./src

RUN python -m compile -b -f -o ./dist ./src
RUN mv -f ./dist/src/* .