from enum import Enum

class Vars(Enum):
    DEBUG_MODE = "DEBUG_MODE"
    API_HOST = "PYTHON_HOST"
    API_PORT =  "PYTHON_PORT"
    API_BASE_PATH = "API_BASE_PATH"
    LOG_LEVEL = "LOG_LEVEL" 
    DIRECTORIO_LOGS = "DIRECTORIO_LOGS"
    DIRECTORIO_FILES = "DIRECTORIO_FILES"
    MONGODB_URL = "MONGODB_URL"
    AUTOCREAR_SENSORES = "AUTOCREAR_SENSORES"
    EMAIL_ENVIADOR = "EMAIL_ENVIADOR"
    EMAIL_PASS = "EMAIL_PASS"
    SMTP_TLS = "SMTP_TLS"
    SMTP_LOGIN = "SMTP_LOGIN"
    SMTP_HOST = "SMTP_HOST"
    SMTP_PORT = "SMTP_PORT"